Retry acceptance test failures 3 times.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -64,11 +64,20 @@ jobs:
         pytest
 
     - name: Acceptance testing
-      run: |
-        set -e
-        # Have to explicitly set MECAB_PATH for natto-py.
-        export MECAB_PATH=/lib/x86_64-linux-gnu/libmecab.so.2
-        inv accept --show --verbose
+      uses: nick-fields/retry@v3
+      with:
+        max_attempts: 3
+        timeout_minutes: 30
+        command: |
+          # handle errors manually, so that the retry works.
+          exit_code=0
+          # Have to explicitly set MECAB_PATH for natto-py.
+          export MECAB_PATH=/lib/x86_64-linux-gnu/libmecab.so.2
+          inv accept --show --verbose || exit_code=$?
+          if [ "$exit_code" -ne 0 ]; then
+              echo "Command failed with exit code $exit_code, retrying..."
+          fi
+          exit $exit_code
 
     # Playwright tests were hanging far too often on github ci,
     # but not consistently.  No idea what was going wrong.
