wip hack

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -69,10 +69,14 @@ jobs:
         max_attempts: 3
         timeout_minutes: 30
         command: |
-          set -e
+          # handle errors manually, so that the retry works.
           # Have to explicitly set MECAB_PATH for natto-py.
           export MECAB_PATH=/lib/x86_64-linux-gnu/libmecab.so.2
-          inv accept --show --verbose -k pretend_failure
+          inv accept --show --verbose -k pretend_failure || exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+              echo "Command failed with exit code $exit_code, retrying..."
+          fi
+          exit $exit_code          
 
     # Playwright tests were hanging far too often on github ci,
     # but not consistently.  No idea what was going wrong.
